In [29]:
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['font.family'] ='Malgun Gothic'
plt.rcParams['axes.unicode_minus'] =False
import seaborn as sns
from glob import glob
from datetime import datetime
import xlwt

In [16]:
files=glob('./data/*.xls')
res=[pd.read_excel(i, header=2)for i in files]
df_raw=pd.concat(res)

In [20]:
df_raw=df_raw.reset_index(drop=True)

In [21]:
df_raw

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
0,경기도,덕양제1주유소,경기 고양시 덕양구 서오릉로 832 (성사동),SK에너지,031-966-5194,Y,1979,1707,1807,-
1,경기도,고양주유소,경기 고양시 덕양구 호국로 730 (성사동),S-OIL,031-962-5534,Y,-,1707,1807,-
2,경기도,(주)어울림주유소,경기 고양시 덕양구 충장로 407,알뜰주유소,031-967-5145,Y,-,1707,1807,-
3,경기도,세일석유㈜ 통일로 일품,경기 고양시 덕양구 통일로 862 (관산동),S-OIL,031-962-8055,Y,-,1707,1807,-
4,경기도,동원2주유소,경기 고양시 덕양구 통일로 1180 (내유동),GS칼텍스,031-969-5148,Y,-,1707,1807,1580
...,...,...,...,...,...,...,...,...,...,...
3052,경기도,조랑말주유소,경기 포천시 이동면 화동로 2469,SK에너지,031-535-7834,Y,-,1995,2095,1800
3053,경기도,금주산주유소,경기 포천시 영중면 영일로 201,자가상표,031-866-5151,N,-,-,1950,1550
3054,경기도,삼정주유소,경기 포천시 이동면 성장로 856,SK에너지,031-535-6671,N,-,-,-,-
3055,경기도,희망주유소,경기 포천시 내촌면 포천로 298,SK에너지,031-532-6440,N,-,-,1785,-
3056,경기도,대박주유소,경기 포천시 군내면 포천로 1066,자가상표,031-542-5184,Y,-,-,-,-

In [25]:
df_raw['날짜']=datetime.now().date()

In [30]:
df_raw.to_excel('./data/통합.xls')

C:\Users\yumei\AppData\Local\Temp\ipykernel_13792\3896570843.py:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  df_raw.to_excel('./data/통합.xls')

In [14]:
len(res)

50

In [9]:
files=glob('./data/*.xls')
res=[]
for i in files:
    tmp=pd.read_excel(i,header=2)
    res.append(tmp)

In [8]:
pd.read_excel('./data/경기도주유소 (1).xls',header=2)

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
0,경기도,덕양제1주유소,경기 고양시 덕양구 서오릉로 832 (성사동),SK에너지,031-966-5194,Y,1979,1707,1807,-
1,경기도,고양주유소,경기 고양시 덕양구 호국로 730 (성사동),S-OIL,031-962-5534,Y,-,1707,1807,-
2,경기도,(주)어울림주유소,경기 고양시 덕양구 충장로 407,알뜰주유소,031-967-5145,Y,-,1707,1807,-
3,경기도,세일석유㈜ 통일로 일품,경기 고양시 덕양구 통일로 862 (관산동),S-OIL,031-962-8055,Y,-,1707,1807,-
4,경기도,동원2주유소,경기 고양시 덕양구 통일로 1180 (내유동),GS칼텍스,031-969-5148,Y,-,1707,1807,1580
...,...,...,...,...,...,...,...,...,...,...
65,경기도,행신주유소,경기 고양시 덕양구 중앙로 394(행신동),SK에너지,031-973-2200,N,-,1933,2033,1848
66,경기도,GS칼텍스 상암주유소,경기 고양시 덕양구 자유로 38 (덕은동),GS칼텍스,02-3158-0030,N,-,2047,2147,1650
67,경기도,(주)원흥 원당동지점,경기 고양시 덕양구 호국로 1113,현대오일뱅크,031-979-5189,Y,-,-,-,-
68,경기도,정미주유소,경기 고양시 덕양구 호국로 1827 (고양동),GS칼텍스,031-963-1155,N,-,-,-,-
69,경기도,주식회사 미래에너지,경기 고양시 덕양구 원당로 367 (원당동),S-OIL,010-8297-6565,Y,-,-,-,-