In [1]:
import pandas as pd
import matplotlib.pyplot as plt   
import numpy as np

In [2]:
df = pd.read_csv('./파일데이터/백내장 -수진월별_수술현황_계__20221202112739.csv',encoding='cp949')
df

,월별(1),항목,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,월별(1),항목,백내장 수술,백내장 수술,백내장 수술,백내장 수술,백내장 수술,백내장 수술,백내장 수술,백내장 수술,백내장 수술,백내장 수술
1,합계,수술인원 (명),308111,302182,-,-,346184,360721,377058,402371,459062,454068
2,합계,수술건수 (건),428158,420905,-,-,491926,518663,549471,592191,689919,702621
3,합계,입원일수 (일),557138,550527,-,-,591335,615637,645675,686969,786119,792205
4,합계,급여일수 (일),1067937,1037330,-,-,1041123,1092803,1111339,1140647,1325513,1278223
...,...,...,...,...,...,...,...,...,...,...,...,...
74,12월,수술건수 (건),37250,31699,40701,39103,45247,51178,48505,53684,63172,75927
75,12월,입원일수 (일),45084,40020,48872,46407,52720,58425,55738,60962,71229,83071
76,12월,급여일수 (일),82968,75874,111698,83565,94049,101391,92093,98272,119162,128839
77,12월,진료비 (천원),35183390,26905399,35091056,35940559,42164886,47912699,46530215,54568051,65206348,85991622
78,12월,급여비 (천원),28316476,21727583,28309194,29001926,34066861,38691033,37579950,44081795,52669122,69312302

In [3]:
df.columns = ['월별(1)', '년도', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018', '2019', '2020']
df = df.set_index(df['년도']).iloc[1:3,2:].transpose()
df

년도   수술인원 (명) 수술건수 (건)
2011   308111   428158
2012   302182   420905
2013        -        -
2014        -        -
2015   346184   491926
2016   360721   518663
2017   377058   549471
2018   402371   592191
2019   459062   689919
2020   454068   702621

In [6]:
df.to_csv('./전처리파일/백내장수술건수.csv')