In [1]:
import pandas as pd
import matplotlib.pyplot as plt   
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
plt.rcParams['font.family'] ='Malgun Gothic'
plt.rcParams['axes.unicode_minus'] =False
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('./파일데이터/연령별_시력_분포_현황_20221202113339.csv',encoding='cp949')
df.head(10)

,연령별(1),성별(1),2011,2011.1,2011.2,2011.3,2011.4,2011.5,2011.6,2011.7,...,2020.6,2020.7,2020.8,2020.9,2020.10,2020.11,2020.12,2020.13,2020.14,2020.15
0,연령별(1),성별(1),좌안 시력,좌안 시력,좌안 시력,좌안 시력,좌안 시력,좌안 시력,좌안 시력,좌안 시력,...,좌안 시력,좌안 시력,우안 시력,우안 시력,우안 시력,우안 시력,우안 시력,우안 시력,우안 시력,우안 시력
1,연령별(1),성별(1),소계,0.1 이하,0.2-0.4,0.5-0.7,0.8-1.0,1.1-1.5,1.6-2.0,기타,...,1.6-2.0,기타,소계,0.1 이하,0.2-0.4,0.5-0.7,0.8-1.0,1.1-1.5,1.6-2.0,기타
2,계,합계,11070569,151956,809720,2050483,4360250,3512604,145119,40437,...,115919,38996,14457022,141001,903292,2790146,6140038,4341026,102896,38623
3,계,남자,6117787,66838,312168,928650,2356250,2323867,108226,21788,...,79640,22450,7598837,54703,354134,1246833,3169332,2679318,72743,21774
4,계,여자,4952782,85118,497552,1121833,2004000,1188737,36893,18649,...,36279,16546,6858185,86298,549158,1543313,2970706,1661708,30153,16849
5,19세 이하,합계,22066,217,1559,3444,8167,8353,315,11,...,149,5,13020,150,901,2080,5252,4504,130,3
6,19세 이하,남자,8912,91,621,1373,3092,3568,164,3,...,111,2,8186,79,520,1264,3267,2958,96,2
7,19세 이하,여자,13154,126,938,2071,5075,4785,151,8,...,38,3,4834,71,381,816,1985,1546,34,1
8,20 ~ 24세,합계,292806,3131,17207,37868,107291,120637,6494,178,...,6260,284,522037,7367,34417,72372,208436,193280,5835,330
9,20 ~ 24세,남자,119895,829,5183,12831,37786,58936,4241,89,...,3931,141,220239,1982,12520,28007,81071,92698,3794,167

In [5]:
df['연령별 성별'] = df['연령별(1)'] + '/' + df['성별(1)']
col = df['연령별 성별']
col.head(10)

0    연령별(1)/성별(1)
1    연령별(1)/성별(1)
2            계/합계
3            계/남자
4            계/여자
5       19세 이하/합계
6       19세 이하/남자
7       19세 이하/여자
8     20 ~ 24세/합계
9     20 ~ 24세/남자
Name: 연령별 성별, dtype: object

In [6]:
df1 = df.T
df1.columns = col
df1 = df1.reset_index()
df1.columns = ['년도', '눈', '시력', '합계/합계', '남자/남자', '여자/여자',
       '19세 이하/합계', '19세 이하/남자', '19세 이하/여자', '20 ~ 24세/합계', '20 ~ 24세/남자',
       '20 ~ 24세/여자', '25 ~ 29세/합계', '25 ~ 29세/남자', '25 ~ 29세/여자',
       '30 ~ 34세/합계', '30 ~ 34세/남자', '30 ~ 34세/여자', '35 ~ 39세/합계',
       '35 ~ 39세/남자', '35 ~ 39세/여자', '40 ~ 44세/합계', '40 ~ 44세/남자',
       '40 ~ 44세/여자', '45 ~ 49세/합계', '45 ~ 49세/남자', '45 ~ 49세/여자',
       '50 ~ 54세/합계', '50 ~ 54세/남자', '50 ~ 54세/여자', '55 ~ 59세/합계',
       '55 ~ 59세/남자', '55 ~ 59세/여자', '60 ~ 64세/합계', '60 ~ 64세/남자',
       '60 ~ 64세/여자', '65 ~ 69세/합계', '65 ~ 69세/남자', '65 ~ 69세/여자',
       '70 ~ 74세/합계', '70 ~ 74세/남자', '70 ~ 74세/여자', '75 ~ 79세/합계',
       '75 ~ 79세/남자', '75 ~ 79세/여자', '80 ~ 84세/합계', '80 ~ 84세/남자',
       '80 ~ 84세/여자', '85세 이상/합계', '85세 이상/남자', '85세 이상/여자']
df1.head(10)

,년도,눈,시력,합계/합계,남자/남자,여자/여자,19세 이하/합계,19세 이하/남자,19세 이하/여자,20 ~ 24세/합계,...,70 ~ 74세/여자,75 ~ 79세/합계,75 ~ 79세/남자,75 ~ 79세/여자,80 ~ 84세/합계,80 ~ 84세/남자,80 ~ 84세/여자,85세 이상/합계,85세 이상/남자,85세 이상/여자
0,연령별(1),연령별(1),연령별(1),계,계,계,19세 이하,19세 이하,19세 이하,20 ~ 24세,...,70 ~ 74세,75 ~ 79세,75 ~ 79세,75 ~ 79세,80 ~ 84세,80 ~ 84세,80 ~ 84세,85세 이상,85세 이상,85세 이상
1,성별(1),성별(1),성별(1),합계,남자,여자,합계,남자,여자,합계,...,여자,합계,남자,여자,합계,남자,여자,합계,남자,여자
2,2011,좌안 시력,소계,11070569,6117787,4952782,22066,8912,13154,292806,...,319420,226827,98895,127932,114366,45860,68506,30616,11609,19007
3,2011.1,좌안 시력,0.1 이하,151956,66838,85118,217,91,126,3131,...,13329,12693,4551,8142,9603,3095,6508,5097,1321,3776
4,2011.2,좌안 시력,0.2-0.4,809720,312168,497552,1559,621,938,17207,...,85280,67015,23605,43410,40824,13740,27084,12821,4478,8343
5,2011.3,좌안 시력,0.5-0.7,2050483,928650,1121833,3444,1373,2071,37868,...,135304,90430,39856,50574,41641,17676,23965,8382,3816,4566
6,2011.4,좌안 시력,0.8-1.0,4360250,2356250,2004000,8167,3092,5075,107291,...,75210,47937,25762,22175,17930,9199,8731,2682,1465,1217
7,2011.5,좌안 시력,1.1-1.5,3512604,2323867,1188737,8353,3568,4785,120637,...,6845,4918,3242,1676,1546,903,643,157,99,58
8,2011.6,좌안 시력,1.6-2.0,145119,108226,36893,315,164,151,6494,...,77,58,34,24,14,8,6,7,1,6
9,2011.7,좌안 시력,기타,40437,21788,18649,11,3,8,178,...,3375,3776,1845,1931,2808,1239,1569,1470,429,1041

In [7]:
df2 = df1[2:].set_index(['년도', '눈', '시력'])
df2 = df2.stack().reset_index()
df2['연령별'] = [i.split('/')[0] for i in df2['level_3']]
df2['성별'] = [i.split('/')[1] for i in df2['level_3']]
del df2['level_3']
df2.columns = ['년도', '눈', '시력', '값', '연령별', '성별']
df2.head(10)

     년도      눈  시력         값       연령별  성별
0  2011  좌안 시력  소계  11070569        합계  합계
1  2011  좌안 시력  소계   6117787        남자  남자
2  2011  좌안 시력  소계   4952782        여자  여자
3  2011  좌안 시력  소계     22066    19세 이하  합계
4  2011  좌안 시력  소계      8912    19세 이하  남자
5  2011  좌안 시력  소계     13154    19세 이하  여자
6  2011  좌안 시력  소계    292806  20 ~ 24세  합계
7  2011  좌안 시력  소계    119895  20 ~ 24세  남자
8  2011  좌안 시력  소계    172911  20 ~ 24세  여자
9  2011  좌안 시력  소계    959981  25 ~ 29세  합계

In [8]:
df3 = df2.set_index(['년도','시력', '눈','성별', '연령별' ]).unstack().reset_index()
df3 = df3.iloc[:-3,:-3]
df3['년도'] = df3['년도'].astype(float).astype('int')
df3['눈'] = [x.replace('안 시력','') for x in df3['눈']]
df3.head(10)

       년도       시력  눈  성별      값                                               \
연령별                       19세 이하 20 ~ 24세 25 ~ 29세 30 ~ 34세 35 ~ 39세 40 ~ 44세
0    2011       소계  좌  남자   8912   119895   538196   809839   776755   686637
1    2011       소계  좌  여자  13154   172911   421785   352154   293600   552265
2    2011       소계  좌  합계  22066   292806   959981  1161993  1070355  1238902
3    2011   0.1 이하  좌  남자     91      829     4187     6061     5483     4755
4    2011   0.1 이하  좌  여자    126     2302     4715     3315     2091     4060
5    2011   0.1 이하  좌  합계    217     3131     8902     9376     7574     8815
6    2011  0.2-0.4  우  남자    644     5529    20489    23469    16107    16933
7    2011  0.2-0.4  우  여자    979    12799    27649    19815    12773    26000
8    2011  0.2-0.4  우  합계   1623    18328    48138    43284    28880    42933
9    2011  0.5-0.7  우  남자   1394    12931    53342    69528    55101    59262

                                                                             \
연령별 45 ~ 49세 50 ~ 54세 55 ~ 59세 60 ~ 64세 65 ~ 69세 70 ~ 74세 75 ~ 79세 80 ~ 84세
0     735724   820436   542879   471320   176091   274739    98895    45860
1     593848   840755   519564   500735   157146   319420   127932    68506
2    1329572  1661191  1062443   972055   333237   594159   226827   114366
3       5903     7553     5627     6070     3299     8013     4551     3095
4       5189     9486     7153    10039     4887    13329     8142     6508
5      11092    17039    12780    16109     8186    21342    12693     9603
6      25020    32258    26375    36715    20720    46847    22830    13218
7      34867    59185    46509    67291    32492    84096    41939    26119
8      59887    91443    72884   104006    53212   130943    64769    39337
9      87844   125490   107902   127396    58934   102926    38813    16908


연령별 85세 이상
0    11609
1    19007
2    30616
3     1321
4     3776
5     5097
6     4291
7     8043
8    12334
9     3727

In [28]:
df4 = df3.T.reset_index()
df4 = df4.set_index('연령별').T[1:]
df4.columns = ['년도', '시력', '눈', '성별', '19세이하', '20 - 24세', '25 - 29세', '30 - 34세',
       '35 - 39세', '40 - 44세', '45 - 49세', '50 - 54세', '55 - 59세', '60 - 64세',
       '65 - 69세', '70 - 74세', '75 - 79세', '80 - 84세', '85세이상']
df4 = df4.set_index(['년도','시력','눈','성별'])
df4.head(10)

                   19세이하 20 - 24세 25 - 29세 30 - 34세 35 - 39세 40 - 44세  \
년도   시력      눈 성별
2011 소계      좌 남자   8912   119895   538196   809839   776755   686637
               여자  13154   172911   421785   352154   293600   552265
               합계  22066   292806   959981  1161993  1070355  1238902
     0.1 이하  좌 남자     91      829     4187     6061     5483     4755
               여자    126     2302     4715     3315     2091     4060
               합계    217     3131     8902     9376     7574     8815
     0.2-0.4 우 남자    644     5529    20489    23469    16107    16933
               여자    979    12799    27649    19815    12773    26000
               합계   1623    18328    48138    43284    28880    42933
     0.5-0.7 우 남자   1394    12931    53342    69528    55101    59262

                  45 - 49세 50 - 54세 55 - 59세 60 - 64세 65 - 69세 70 - 74세  \
년도   시력      눈 성별
2011 소계      좌 남자   735724   820436   542879   471320   176091   274739
               여자   593848   840755   519564   500735   157146   319420
               합계  1329572  1661191  1062443   972055   333237   594159
     0.1 이하  좌 남자     5903     7553     5627     6070     3299     8013
               여자     5189     9486     7153    10039     4887    13329
               합계    11092    17039    12780    16109     8186    21342
     0.2-0.4 우 남자    25020    32258    26375    36715    20720    46847
               여자    34867    59185    46509    67291    32492    84096
               합계    59887    91443    72884   104006    53212   130943
     0.5-0.7 우 남자    87844   125490   107902   127396    58934   102926

                  75 - 79세 80 - 84세  85세이상
년도   시력      눈 성별
2011 소계      좌 남자    98895    45860  11609
               여자   127932    68506  19007
               합계   226827   114366  30616
     0.1 이하  좌 남자     4551     3095   1321
               여자     8142     6508   3776
               합계    12693     9603   5097
     0.2-0.4 우 남자    22830    13218   4291
               여자    41939    26119   8043
               합계    64769    39337  12334
     0.5-0.7 우 남자    38813    16908   3727

In [29]:
df4['합계'] = df4[:].replace('-','0').astype(int).sum(axis=1)
df4 = df4[['합계','19세이하', '20 - 24세', '25 - 29세', '30 - 34세', '35 - 39세', '40 - 44세',
       '45 - 49세', '50 - 54세', '55 - 59세', '60 - 64세', '65 - 69세', '70 - 74세',
       '75 - 79세', '80 - 84세', '85세이상']]
df4

                        합계  19세이하 20 - 24세 25 - 29세 30 - 34세 35 - 39세  \
년도   시력     눈 성별
2011 소계     좌 남자   6117787   8912   119895   538196   809839   776755
              여자   4952782  13154   172911   421785   352154   293600
              합계  11070569  22066   292806   959981  1161993  1070355
     0.1 이하 좌 남자     66838     91      829     4187     6061     5483
              여자     85118    126     2302     4715     3315     2091
...                    ...    ...      ...      ...      ...      ...
2020 소계     우 여자   6858185   4834   301798   515835   502951   446718
              합계  14457022  13020   522037  1085087  1224234  1197704
     0.1 이하 우 남자     54703     79     1982     3081     3003     2622
              여자     86298     71     5385     5675     4345     2754
              합계    141001    150     7367     8756     7348     5376

                 40 - 44세 45 - 49세 50 - 54세 55 - 59세 60 - 64세 65 - 69세  \
년도   시력     눈 성별
2011 소계     좌 남자   686637   735724   820436   542879   471320   176091
              여자   552265   593848   840755   519564   500735   157146
              합계  1238902  1329572  1661191  1062443   972055   333237
     0.1 이하 좌 남자     4755     5903     7553     5627     6070     3299
              여자     4060     5189     9486     7153    10039     4887
...                   ...      ...      ...      ...      ...      ...
2020 소계     우 여자   716905   677524   906023   739234   836511   456538
              합계  1644860  1508790  1838588  1489820  1609459   897727
     0.1 이하 우 남자     3609     3699     4673     4228     5864     4708
              여자     4626     5129     6953     5865     9484     7458
              합계     8235     8828    11626    10093    15348    12166

                 70 - 74세 75 - 79세 80 - 84세  85세이상
년도   시력     눈 성별
2011 소계     좌 남자   274739    98895    45860  11609
              여자   319420   127932    68506  19007
              합계   594159   226827   114366  30616
     0.1 이하 좌 남자     8013     4551     3095   1321
              여자    13329     8142     6508   3776
...                   ...      ...      ...    ...
2020 소계     우 여자   390258   197116   127750  38190
              합계   756510   372426   234591  62169
     0.1 이하 우 남자     6307     4707     4407   1734
              여자     9517     7354     7003   4679
              합계    15824    12061    11410   6413

[480 rows x 16 columns]

In [24]:
df4.to_csv('./전처리파일/연령별시력.csv')

In [29]:
eye = pd.read_csv('./전처리파일/연령별시력.csv')
eye = eye.replace('-','0')
eye.head(10)

,년도,시력,눈,성별,합계,19세이하,20 - 24세,25 - 29세,30 - 34세,35 - 39세,40 - 44세,45 - 49세,50 - 54세,55 - 59세,60 - 64세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85세이상
0,2011,소계,좌,남자,6117787,8912,119895,538196,809839,776755,686637,735724,820436,542879,471320,176091,274739,98895,45860,11609
1,2011,소계,좌,여자,4952782,13154,172911,421785,352154,293600,552265,593848,840755,519564,500735,157146,319420,127932,68506,19007
2,2011,소계,좌,합계,11070569,22066,292806,959981,1161993,1070355,1238902,1329572,1661191,1062443,972055,333237,594159,226827,114366,30616
3,2011,0.1 이하,좌,남자,66838,91,829,4187,6061,5483,4755,5903,7553,5627,6070,3299,8013,4551,3095,1321
4,2011,0.1 이하,좌,여자,85118,126,2302,4715,3315,2091,4060,5189,9486,7153,10039,4887,13329,8142,6508,3776
5,2011,0.1 이하,좌,합계,151956,217,3131,8902,9376,7574,8815,11092,17039,12780,16109,8186,21342,12693,9603,5097
6,2011,0.2-0.4,우,남자,311445,644,5529,20489,23469,16107,16933,25020,32258,26375,36715,20720,46847,22830,13218,4291
7,2011,0.2-0.4,우,여자,500556,979,12799,27649,19815,12773,26000,34867,59185,46509,67291,32492,84096,41939,26119,8043
8,2011,0.2-0.4,우,합계,812001,1623,18328,48138,43284,28880,42933,59887,91443,72884,104006,53212,130943,64769,39337,12334
9,2011,0.5-0.7,우,남자,921498,1394,12931,53342,69528,55101,59262,87844,125490,107902,127396,58934,102926,38813,16908,3727

In [4]:
eye['시력'].unique()

array(['소계', '0.1 이하', '0.2-0.4', '0.5-0.7', '0.8-1.0', '1.1-1.5',
       '1.6-2.0', '기타'], dtype=object)

In [25]:
eye[(eye['시력']=='소계') & (eye['성별']=='합계')]

,년도,시력,눈,성별,합계,19세이하,20 - 24세,25 - 29세,30 - 34세,35 - 39세,40 - 44세,45 - 49세,50 - 54세,55 - 59세,60 - 64세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85세이상
2,2011,소계,좌,합계,11070569,22066,292806,959981,1161993,1070355,1238902,1329572,1661191,1062443,972055,333237,594159,226827,114366,30616
44,2011,소계,우,합계,11070569,22066,292806,959981,1161993,1070355,1238902,1329572,1661191,1062443,972055,333237,594159,226827,114366,30616
50,2012,소계,좌,합계,11415301,25843,289849,861295,1181671,1082964,1274327,1361065,1759161,1151948,1052817,322349,647991,244935,128418,30668
92,2012,소계,우,합계,11377978,25829,289683,860811,1180695,1081935,1272537,1358708,1754752,1148181,1046859,319781,641121,241388,125944,29754
98,2013,소계,좌,합계,11377411,30392,310514,879214,1206141,1020498,1304472,1371099,1646953,1204495,1004241,317990,638099,267087,138899,37317
140,2013,소계,우,합계,11381295,30395,310544,879338,1206389,1020708,1304791,1371396,1647344,1204758,1004503,318096,638440,267378,139344,37871
146,2014,소계,좌,합계,12301581,28855,320157,886824,1232766,1139037,1330964,1512407,1801231,1337416,1162690,362290,684102,293277,165798,43767
188,2014,소계,우,합계,12301581,28855,320157,886824,1232766,1139037,1330964,1512407,1801231,1337416,1162690,362290,684102,293277,165798,43767
194,2015,소계,좌,합계,14025411,27898,331153,906928,1271907,1193888,1943090,1653299,1885250,1492845,1285409,767155,687162,334352,193357,51718
236,2015,소계,우,합계,14025411,27898,331153,906928,1271907,1193888,1943090,1653299,1885250,1492845,1285409,767155,687162,334352,193357,51718
242,2016,소계,좌,합계,14548392,27698,348864,974937,1203259,1231963,1942299,1729097,1895002,1586881,1456209,778442,756759,343885,217859,55238
284,2016,소계,우,합계,14548392,27698,348864,974937,1203259,1231963,1942299,1729097,1895002,1586881,1456209,778442,756759,343885,217859,55238
290,2017,소계,좌,합계,14805207,25498,340926,972343,1166903,1267513,1931232,1751848,1907258,1644551,1551359,789398,764036,387835,241803,62704
332,2017,소계,우,합계,14805207,25498,340926,972343,1166903,1267513,1931232,1751848,1907258,1644551,1551359,789398,764036,387835,241803,62704
338,2018,소계,좌,합계,15076899,21548,337873,1008398,1195162,1335464,1839238,1732167,1965960,1662173,1597421,868891,778593,416163,253020,64828
380,2018,소계,우,합계,15076899,21548,337873,1008398,1195162,1335464,1839238,1732167,1965960,1662173,1597421,868891,778593,416163,253020,64828
386,2019,소계,좌,합계,16094992,16160,544312,1144648,1340518,1385778,1918822,1767554,2055219,1648134,1780238,860180,850653,414269,291760,76747
428,2019,소계,우,합계,16094992,16160,544312,1144648,1340518,1385778,1918822,1767554,2055219,1648134,1780238,860180,850653,414269,291760,76747
434,2020,소계,좌,합계,14457022,13020,522037,1085087,1224234,1197704,1644860,1508790,1838588,1489820,1609459,897727,756510,372426,234591,62169
476,2020,소계,우,합계,14457022,13020,522037,1085087,1224234,1197704,1644860,1508790,1838588,1489820,1609459,897727,756510,372426,234591,62169

In [27]:
eye[(eye['년도']==2020) & (eye['시력']!='소계') & (eye['성별']=='남자')]

,년도,시력,눈,성별,합계,19세이하,20 - 24세,25 - 29세,30 - 34세,35 - 39세,40 - 44세,45 - 49세,50 - 54세,55 - 59세,60 - 64세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85세이상
435,2020,0.1 이하,좌,남자,54318,69,1648,2524,2851,2584,3726,3763,4755,4357,6006,4868,6205,4741,4484,1737
438,2020,0.2-0.4,우,남자,354134,520,12520,23259,23249,18084,23852,25524,31512,27066,39736,33025,39148,27359,22457,6823
441,2020,0.5-0.7,우,남자,1246833,1264,28007,62917,72411,65852,87653,101355,133714,131088,180829,130348,129641,69405,43195,9154
444,2020,0.8-1.0,우,남자,3169332,3267,81071,205929,261745,270786,353383,355865,428494,365051,380854,208981,156145,61692,31036,5033
447,2020,1.1-1.5,우,남자,2679318,2958,92698,264582,348905,380692,444436,335285,325494,217344,160300,60996,31473,9777,3843,535
450,2020,1.6-2.0,우,남자,72743,96,3794,9153,11506,12344,13851,8209,6688,3678,2291,695,325,81,30,2
453,2020,기타,우,남자,21774,2,167,331,464,606,1171,1329,1990,2131,3074,2436,3213,2289,1873,698
456,2020,0.2-0.4,좌,남자,353881,464,11358,20977,21684,17649,22952,25151,31591,27827,41315,33999,40220,28502,23164,7028
459,2020,0.5-0.7,좌,남자,1262618,1276,28112,61957,71254,65326,88245,102330,136318,134112,185207,132768,132205,70267,44045,9196
462,2020,0.8-1.0,좌,남자,3146769,3238,81564,205658,260393,268138,352364,356161,426938,360707,376046,206713,153935,60387,29621,4906
465,2020,1.1-1.5,좌,남자,2679161,3026,93485,268268,352340,383221,443896,333041,323534,217120,158655,59619,30051,8975,3493,437
468,2020,1.6-2.0,좌,남자,79640,111,3931,9535,12232,13415,15586,9379,7389,4293,2564,778,297,90,36,4
471,2020,기타,좌,남자,22450,2,141,333,529,653,1186,1441,2040,2170,3155,2444,3339,2348,1998,671
477,2020,0.1 이하,우,남자,54703,79,1982,3081,3003,2622,3609,3699,4673,4228,5864,4708,6307,4707,4407,1734

In [28]:
eye[(eye['년도']==2020) & (eye['시력']!='소계') & (eye['성별']=='여자')]

,년도,시력,눈,성별,합계,19세이하,20 - 24세,25 - 29세,30 - 34세,35 - 39세,40 - 44세,45 - 49세,50 - 54세,55 - 59세,60 - 64세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85세이상
436,2020,0.1 이하,좌,여자,80417,67,4059,4610,3816,2686,4371,4774,6963,5641,8709,6903,9020,7083,7006,4709
439,2020,0.2-0.4,우,여자,549158,381,21897,29340,26490,18939,32887,38506,52360,43755,70544,54594,64544,44876,36110,13935
442,2020,0.5-0.7,우,여자,1543313,816,44365,67268,63753,52060,94827,116597,181036,177686,261377,171726,161957,84000,52724,13121
445,2020,0.8-1.0,우,여자,2970706,1985,127365,216279,207014,183615,304730,314541,442623,370958,392636,188766,134348,53257,27537,5052
448,2020,1.1-1.5,우,여자,1661708,1546,100582,193092,196813,184666,273084,198568,218857,138138,99272,31903,16897,5497,2457,336
451,2020,1.6-2.0,우,여자,30153,34,2041,3934,4288,4384,6180,3519,3000,1487,870,221,134,38,16,7
454,2020,기타,우,여자,16849,1,163,247,248,300,571,664,1194,1345,2328,1870,2861,2094,1903,1060
457,2020,0.2-0.4,좌,여자,540717,357,19940,26423,24659,18172,31341,37232,51958,43445,70076,54099,65228,45778,37662,14347
460,2020,0.5-0.7,좌,여자,1553355,790,45345,67850,64118,51675,94031,117280,183157,177788,262738,173317,163994,85214,52952,13106
463,2020,0.8-1.0,좌,여자,2946290,1986,128915,216438,205726,181546,301973,310874,436921,367612,390676,187953,132683,52085,26232,4670
466,2020,1.1-1.5,좌,여자,1684581,1593,101067,196014,199502,186997,276797,202209,221999,141536,100960,32163,16459,4934,2072,279
469,2020,1.6-2.0,좌,여자,36279,38,2329,4280,4881,5337,7713,4478,3802,1875,1041,305,137,44,15,4
472,2020,기타,좌,여자,16546,3,143,220,249,305,679,677,1223,1337,2311,1798,2737,1978,1811,1075
478,2020,0.1 이하,우,여자,86298,71,5385,5675,4345,2754,4626,5129,6953,5865,9484,7458,9517,7354,7003,4679