In [1]:
from glob import glob
from PIL import Image
import numpy as np

x,y = [],[]
folderList = glob('./clothes_dataset/*')
folderList

['./clothes_dataset\\black_dress',
 './clothes_dataset\\black_pants',
 './clothes_dataset\\black_shirt',
 './clothes_dataset\\black_shoes',
 './clothes_dataset\\black_shorts',
 './clothes_dataset\\blue_dress',
 './clothes_dataset\\blue_pants',
 './clothes_dataset\\blue_shirt',
 './clothes_dataset\\blue_shoes',
 './clothes_dataset\\blue_shorts',
 './clothes_dataset\\brown_pants',
 './clothes_dataset\\brown_shoes',
 './clothes_dataset\\brown_shorts',
 './clothes_dataset\\green_pants',
 './clothes_dataset\\green_shirt',
 './clothes_dataset\\green_shoes',
 './clothes_dataset\\green_shorts',
 './clothes_dataset\\red_dress',
 './clothes_dataset\\red_pants',
 './clothes_dataset\\red_shoes',
 './clothes_dataset\\white_dress',
 './clothes_dataset\\white_pants',
 './clothes_dataset\\white_shoes',
 './clothes_dataset\\white_shorts']

In [2]:
for cnt,folder in enumerate(folderList):
    fileList = glob(folder + '/*.jpg')
    print('>Start:'+folder)
    for file in fileList:
        img = Image.open(file)
        img = img.resize((180,180))
        imgArr = np.array(img)
        x.append(imgArr)
        y.append(cnt)

>Start:./clothes_dataset\black_dress
>Start:./clothes_dataset\black_pants
>Start:./clothes_dataset\black_shirt
>Start:./clothes_dataset\black_shoes
>Start:./clothes_dataset\black_shorts
>Start:./clothes_dataset\blue_dress
>Start:./clothes_dataset\blue_pants
>Start:./clothes_dataset\blue_shirt
>Start:./clothes_dataset\blue_shoes
>Start:./clothes_dataset\blue_shorts
>Start:./clothes_dataset\brown_pants
>Start:./clothes_dataset\brown_shoes
>Start:./clothes_dataset\brown_shorts
>Start:./clothes_dataset\green_pants
>Start:./clothes_dataset\green_shirt
>Start:./clothes_dataset\green_shoes
>Start:./clothes_dataset\green_shorts
>Start:./clothes_dataset\red_dress
>Start:./clothes_dataset\red_pants
>Start:./clothes_dataset\red_shoes
>Start:./clothes_dataset\white_dress
>Start:./clothes_dataset\white_pants
>Start:./clothes_dataset\white_shoes
>Start:./clothes_dataset\white_shorts

In [3]:
np.shape(x), np.shape(y)

((11385, 180, 180, 3), (11385,))

In [16]:
np.savez('clothes.npz',  Xdata = x, Ydata = y)

In [4]:
y[445:459]

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [5]:
data = np.load('clothes.npz')
list(data)

['Xdata', 'Ydata']

In [6]:
Xdata = data['Xdata']
Ydata = data['Ydata']

In [7]:
Xdata

array([[[[  5,   3,   4],
         [  8,   6,   7],
         [  3,   1,   2],
         ...,
         [  1,   1,   1],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  4,   2,   3],
         [ 10,   8,   9],
         [  2,   1,   1],
         ...,
         [  1,   1,   1],
         [  0,   0,   0],
         [  1,   1,   1]],

        [[  6,   4,   5],
         [ 10,   8,   9],
         [  4,   2,   3],
         ...,
         [  1,   1,   1],
         [  0,   0,   0],
         [  1,   1,   1]],

        ...,

        [[150,  39,  46],
         [146,  34,  41],
         [141,  29,  37],
         ...,
         [159,  45,  51],
         [156,  43,  49],
         [157,  43,  50]],

        [[137,  34,  38],
         [141,  34,  39],
         [147,  36,  42],
         ...,
         [160,  48,  54],
         [160,  48,  54],
         [155,  44,  50]],

        [[141,  43,  44],
         [135,  31,  34],
         [148,  38,  43],
         ...,
         [163,  50,  56],
         [162,  50,  56],
         [159,  48,  54]]],


       [[[224, 223, 221],
         [221, 220, 218],
         [221, 220, 218],
         ...,
         [224, 223, 221],
         [222, 221, 219],
         [225, 224, 222]],

        [[222, 221, 219],
         [218, 217, 215],
         [219, 218, 216],
         ...,
         [220, 219, 217],
         [218, 217, 215],
         [222, 221, 219]],

        [[222, 221, 219],
         [220, 219, 217],
         [220, 219, 217],
         ...,
         [220, 219, 217],
         [220, 219, 217],
         [223, 222, 220]],

        ...,

        [[243, 241, 236],
         [239, 236, 231],
         [237, 235, 230],
         ...,
         [238, 237, 233],
         [238, 237, 233],
         [243, 242, 238]],

        [[243, 242, 238],
         [238, 237, 233],
         [237, 237, 233],
         ...,
         [237, 236, 232],
         [237, 236, 232],
         [242, 241, 237]],

        [[241, 240, 236],
         [239, 238, 234],
         [241, 240, 236],
         ...,
         [241, 240, 236],
         [241, 240, 236],
         [241, 240, 236]]],


       [[[ 89, 105, 128],
         [121, 136, 158],
         [151, 163, 183],
         ...,
         [ 66,  67,  69],
         [ 32,  33,  35],
         [  9,  10,  12]],

        [[ 87, 103, 126],
         [118, 134, 156],
         [148, 160, 180],
         ...,
         [ 80,  81,  83],
         [ 70,  71,  73],
         [ 47,  48,  50]],

        [[ 89, 105, 128],
         [118, 133, 155],
         [149, 161, 181],
         ...,
         [ 67,  68,  70],
         [ 76,  77,  79],
         [ 80,  81,  83]],

        ...,

        [[ 55,  73,  91],
         [ 65,  82, 106],
         [ 54,  71,  99],
         ...,
         [ 60,  76, 101],
         [ 66,  83, 108],
         [ 57,  73,  98]],

        [[ 52,  71,  89],
         [ 68,  85, 109],
         [ 59,  76, 104],
         ...,
         [ 55,  70,  93],
         [ 56,  71,  94],
         [ 64,  80, 103]],

        [[ 79,  98, 116],
         [ 61,  79, 103],
         [ 51,  68,  96],
         ...,
         [ 41,  55,  76],
         [ 44,  59,  80],
         [ 67,  82, 103]]],


       ...,


       [[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]],


       [[[253, 253, 253],
         [249, 249, 249],
         [249, 249, 249],
         ...,
         [236, 237, 239],
         [236, 237, 239],
         [245, 246, 247]],

        [[251, 251, 251],
         [244, 244, 244],
         [245, 245, 245],
         ...,
         [229, 230, 232],
         [229, 230, 232],
         [240, 241, 243]],

        [[251, 251, 251],
         [243, 243, 243],
         [243, 243, 243],
         ...,
         [229, 230, 232],
         [229, 230, 232],
         [240, 241, 243]],

        ...,

        [[237, 240, 248],
         [225, 228, 237],
         [224, 227, 236],
         ...,
         [227, 231, 240],
         [227, 231, 240],
         [238, 242, 251]],

        [[235, 238, 245],
         [225, 228, 234],
         [225, 228, 234],
         ...,
         [226, 230, 236],
         [226, 230, 236],
         [238, 242, 248]],

        [[240, 243, 248],
         [233, 236, 241],
         [232, 235, 240],
         ...,
         [233, 236, 241],
         [233, 236, 241],
         [238, 241, 246]]],


       [[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]]], dtype=uint8)

In [8]:
Ydata

array([ 0,  0,  0, ..., 23, 23, 23])

In [9]:
class_name = []
for i in folderList:
    class_name.append(i.split('\\')[-1])
class_name

['black_dress',
 'black_pants',
 'black_shirt',
 'black_shoes',
 'black_shorts',
 'blue_dress',
 'blue_pants',
 'blue_shirt',
 'blue_shoes',
 'blue_shorts',
 'brown_pants',
 'brown_shoes',
 'brown_shorts',
 'green_pants',
 'green_shirt',
 'green_shoes',
 'green_shorts',
 'red_dress',
 'red_pants',
 'red_shoes',
 'white_dress',
 'white_pants',
 'white_shoes',
 'white_shorts']

In [10]:
import os
os.listdir('./clothes_dataset/')

['black_dress',
 'black_pants',
 'black_shirt',
 'black_shoes',
 'black_shorts',
 'blue_dress',
 'blue_pants',
 'blue_shirt',
 'blue_shoes',
 'blue_shorts',
 'brown_pants',
 'brown_shoes',
 'brown_shorts',
 'green_pants',
 'green_shirt',
 'green_shoes',
 'green_shorts',
 'red_dress',
 'red_pants',
 'red_shoes',
 'white_dress',
 'white_pants',
 'white_shoes',
 'white_shorts']

In [11]:
color_list = [x.split('_')[0] for x in class_name]
cartegory_list = [x.split('_')[1] for x in class_name]
color = list(set(color_list))
cartegory = list(set(cartegory_list))

In [12]:
color

['brown', 'green', 'red', 'black', 'white', 'blue']

In [13]:
cartegory

['shoes', 'pants', 'dress', 'shirt', 'shorts']

In [14]:
# 방법1은 _와 특수형태문자 반응을 잘 못함
import os
folderList = os.listdir('./clothes_dataset/')
itemList = []
for x in folderList:
    itemList.append([])
    itemList[-1].append(x.split('_')[0])
    itemList[-1].append(x.split('_')[1])
itemList = np.array(itemList)
item = []
item.append(list(set(itemList[:,0])))
item.append(list(set(itemList[:,1])))
item

[['brown', 'green', 'red', 'black', 'white', 'blue'],
 ['shoes', 'pants', 'dress', 'shirt', 'shorts']]

In [15]:
import os
import numpy as np
#folderName='clothes_dataset'
#splitVar='_'
folderName=input('폴더명 작성하세요: ')
splitVar=input('나눌 문자 작성하세요: ')
folder='./' + folderName +'/'
folderList=os.listdir(folder)

itemList=[]
for x in folderList:
    itemList.append([])

    for cnt in range(len(x.split(splitVar))):
        itemList[-1].append(x.split(splitVar)[cnt])
        
itemList=np.array(itemList)    
item=[]

for x in range(np.shape(itemList)[1]):
    item.append(list(set(itemList[:,x])))
item

[['brown', 'green', 'red', 'black', 'white', 'blue'],
 ['shoes', 'pants', 'dress', 'shirt', 'shorts']]

In [16]:
# 깔끔한 코드
import os
import numpy as np

folderName=input('폴더명 작성하세요: ')
splitVar=input('나눌 문자 작성하세요: ')
folder='./' + folderName +'/'
folderList=os.listdir(folder)

itemList = [x.split(splitVar) for x in folderList]
itemList = np.array(itemList)

item = [list(set(itemList[:,x]))for x in range(np.shape(itemList[1]))]
item

TypeError: 'tuple' object cannot be interpreted as an integer

In [17]:
var = [[1,2],
        [2,3],
        [4,5],
        [2,1]]
var = np.array(var)
np.sum(var[:,0])

9

In [18]:
var[:,0][var[:,0]>=2]=2000
var

array([[   1,    2],
       [2000,    3],
       [2000,    5],
       [2000,    1]])

In [36]:
from glob import glob
folderName = './clothes_dataset/'
folderList = glob( folderName + '/*')
x = folderList[0].split('\\')[-1]

tmp = x.split('_')[0]
item[0].index(tmp)

3

In [37]:
# 멀티 데이터 제작
y = []
for folder in folderList:
    tmp1 = folder.split('_')[0]
    y.append(item[0].index(tmp1))

    tmp2 = folder.split('_')[1]
    y[-1].append(item[0].index(tmp2))

    print('>Start:'+folder)
    for file in fileList:
        img = Image.open(file)
        img = img.resize((180,180))
        imgArr = np.array(img)
        x.append(imgArr)
        y.append(cnt)

ValueError: './clothes' is not in list

In [21]:
from glob import glob
from PIL import Image
import numpy as np
x,y=[],[]
folderList=glob('./clothes_dataset/*')

for folder in folderList[:3]:
    fileList=glob(folder + '/*.jpg')
    
    folderSplitName=folder.split('\\')[-1]
    colorName=folderSplitName.split('_')[0]
    colorNum=color.index(colorName)
    
    categoryName=folderSplitName.split('_')[1]
    categoryNum=cartegory.index(categoryName)
       
    print('▶️ Start:' + folder)
    for file in fileList:
        img=Image.open(file)
        img=img.resize((180,180))
        imgArr=np.array(img)
        x.append(imgArr)
        y.append([])
        y[-1].append(colorNum)
        y[-1].append(categoryNum)

▶️ Start:./clothes_dataset\black_dress
▶️ Start:./clothes_dataset\black_pants
▶️ Start:./clothes_dataset\black_shirt

In [22]:
np.savez('cloths_multi_label.npz',Xdata=x, Ydata=y,class_name=item)

c:\Users\user\.conda\envs\han\lib\site-packages\numpy\lib\npyio.py:696: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  val = np.asanyarray(val)

In [39]:
# 풀더명을 csv로 제작
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from glob import glob

folderName = glob('./clothes_dataset/*')
dataList = []

for folder in folderName:
    fileList = glob( folder + './*jpg') 
    for file in fileList:

# file = './clothes_dataset\\white_shorts.\\fd76a8fe7e6c5d2fe5f346c3207f75325a781d82.jpg'

        fileName = file
        colorName = file.split('\\')[1].split('_')[0]
        categoryName = file.split('\\')[1].split('_')[-1].replace('.','')
        
        dataList.append({'Name':fileName, 
                        'colorName':colorName, 
                        'categoryName':categoryName})
df = pd.DataFrame(dataList)
df

,Name,colorName,categoryName
0,./clothes_dataset\black_dress.\0097960878307e5...,black,dress
1,./clothes_dataset\black_dress.\038098f911bf304...,black,dress
2,./clothes_dataset\black_dress.\0522170fba54aa3...,black,dress
3,./clothes_dataset\black_dress.\0561718aec3cca9...,black,dress
4,./clothes_dataset\black_dress.\06130b80c92914d...,black,dress
...,...,...,...
11380,./clothes_dataset\white_shorts.\f0be9c6655655f...,white,shorts
11381,./clothes_dataset\white_shorts.\f35256887334f9...,white,shorts
11382,./clothes_dataset\white_shorts.\f50bf2c5e771f7...,white,shorts
11383,./clothes_dataset\white_shorts.\fb625925bc55cd...,white,shorts
11384,./clothes_dataset\white_shorts.\fd76a8fe7e6c5d...,white,shorts

In [40]:
# 원핫인코딩
pd.get_dummies(df[['colorName','categoryName']])

,colorName_black,colorName_blue,colorName_brown,colorName_green,colorName_red,colorName_white,categoryName_dress,categoryName_pants,categoryName_shirt,categoryName_shoes,categoryName_shorts
0,1,0,0,0,0,0,1,0,0,0,0
1,1,0,0,0,0,0,1,0,0,0,0
2,1,0,0,0,0,0,1,0,0,0,0
3,1,0,0,0,0,0,1,0,0,0,0
4,1,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
11380,0,0,0,0,0,1,0,0,0,0,1
11381,0,0,0,0,0,1,0,0,0,0,1
11382,0,0,0,0,0,1,0,0,0,0,1
11383,0,0,0,0,0,1,0,0,0,0,1
11384,0,0,0,0,0,1,0,0,0,0,1

In [42]:
# 원핫인코딩 
df1 = pd.get_dummies(df, columns=['colorName','categoryName'])     # 모든 컬럼스 출력
df1.columns=['Name', 'black', 'blue', 'brown','green', 'red', 'white','dress', 'pants', 'shirt','shoes', 'shorts']
df1.to_csv('./train.csv')  
df1.to_csv('./val.csv')  
df1

,Name,black,blue,brown,green,red,white,dress,pants,shirt,shoes,shorts
0,./clothes_dataset\black_dress.\0097960878307e5...,1,0,0,0,0,0,1,0,0,0,0
1,./clothes_dataset\black_dress.\038098f911bf304...,1,0,0,0,0,0,1,0,0,0,0
2,./clothes_dataset\black_dress.\0522170fba54aa3...,1,0,0,0,0,0,1,0,0,0,0
3,./clothes_dataset\black_dress.\0561718aec3cca9...,1,0,0,0,0,0,1,0,0,0,0
4,./clothes_dataset\black_dress.\06130b80c92914d...,1,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
11380,./clothes_dataset\white_shorts.\f0be9c6655655f...,0,0,0,0,0,1,0,0,0,0,1
11381,./clothes_dataset\white_shorts.\f35256887334f9...,0,0,0,0,0,1,0,0,0,0,1
11382,./clothes_dataset\white_shorts.\f50bf2c5e771f7...,0,0,0,0,0,1,0,0,0,0,1
11383,./clothes_dataset\white_shorts.\fb625925bc55cd...,0,0,0,0,0,1,0,0,0,0,1
11384,./clothes_dataset\white_shorts.\fd76a8fe7e6c5d...,0,0,0,0,0,1,0,0,0,0,1

In [33]:
from PIL import Image
import numpy as np

train=[]
df=pd.read_csv('train.csv')

X = []
for x in df['Name']:
    img = Image.open(x)
    img = img.resize((180,180))
    imgArr = np.array(img)
    X.append(imgArr)

color,category = [],[]
color.append(df[['black', 'blue', 'brown','green', 'red', 'white']].values)
cartegory.append(df[['dress', 'pants', 'shirt','shoes', 'shorts']].values)

train = []
train.append(x)
train.append(color)
train.append(cartegory)

In [34]:
from PIL import Image
import numpy as np

val=[]
df=pd.read_csv('val.csv')

X = []
for x in df['Name']:
    img = Image.open(x)
    img = img.resize((180,180))
    imgArr = np.array(img)
    X.append(imgArr)

color,category = [],[]
color.append(df[['black', 'blue', 'brown','green', 'red', 'white']].values)
cartegory.append(df[['dress', 'pants', 'shirt','shoes', 'shorts']].values)

val = []
val.append(x)
val.append(color)
val.append(cartegory)